exec env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1

bindsym $alt+Space       exec swayr switch-window
bindsym $alt+Delete      exec swayr quit-window
bindsym $alt+Tab         exec swayr switch-to-urgent-or-lru-window
bindsym $alt+Next        exec swayr next-window all-workspaces
bindsym $alt+Prior       exec swayr prev-window all-workspaces
bindsym $alt+Shift+Space exec swayr switch-workspace-or-window
bindsym $alt+c           exec swayr execute-swaymsg-command
bindsym $alt+Shift+c     exec swayr execute-swayr-command
