#!/bin/bash

if command -v swaybg &>/dev/null; then

  wallpaper_dir=${WALLPAPERS:-$HOME/.local/share/wallpapers}/$1
  [[ -f "$1" ]] && wallpaper=$1 || wallpaper=$(find "$wallpaper_dir" -type f | shuf -n 1 --random-source=/dev/urandom)
  wallpaper=$(realpath "$wallpaper")

  if [[ -f "$wallpaper" ]]; then
    echo $(realpath --relative-to="$wallpaper_dir" "$wallpaper")
    [ -n "$TMUX" ] && runner='tmux run-shell' || runner=eval
    $runner "swaymsg \"output * bg \"$wallpaper\" fill\"" &>/dev/null
  fi

fi
