# -*- conf -*-

include=~/.foot.ini

[scrollback]
lines=10000

[key-bindings]
clipboard-paste=Control+v XF86Paste

[text-bindings]
\x17 = Control+BackSpace

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape

[mouse]
hide-when-typing=yes
